### ISSUE TITLE
Support AttrDict inside arrays of dicts

### ISSUE THREAD

**Issue by kirsle** [KyleJamesWalker/yamlsettings#3]
Given this defaults.yml:

``` yaml
server:
    daemon:
        setuid: nobody

    services:
        - smtp25:
            protocol: SMTP
            host: localhost
            port: 25
        - smtp587:
            protocol: SMTP
            host: localhost
            port: 587
        - imap:
            protocol: IMAP
            host: localhost
            port: 143
```

And Python code:

``` python
import yamlsettings

settings = yamlsettings.YamlSettings("defaults.yml",
    "settings.yml",
    default_section="server",
)
base_settings = settings.get_settings()

from pprint import pprint
pprint(base_settings)
```

The output is (reformatted for clarity):

``` python
AttrDict([
    ('daemon', AttrDict([
        ('setuid', 'nobody')
    ])),

    ('services', [
        OrderedDict([('smtp25', OrderedDict([
                ('protocol', 'SMTP'),
                ('host', 'localhost'),
                ('port', 25)
            ]))
        ]),
        OrderedDict([('smtp587', OrderedDict([
                ('protocol', 'SMTP'),
                ('host', 'localhost'),
                ('port', 587)
            ]))
        ]),
        OrderedDict([('imap', OrderedDict([
                ('protocol', 'IMAP'),
                ('host', 'localhost'),
                ('port', 143)
            ]))
        ])
    ])
])
```

Code to access items from the settings:

``` python
print base_settings.daemon.setuid
print base_settings.services[0]["smtp25"]["port"]
```

**What I wanted to happen:**

All dicts would be AttrDict.

The ideal syntax to access the array dicts would be something along the lines of,

``` python
print base_settings.services[0].port
# or instead, maybe,
print base_settings.services["smtp25"].port
```

...although I dunno how feasible that would be.

**What Actually Happens:**

The dicts inside the array become OrderedDict.
